export default function Home() {
  return (
    <main className="min-h-screen bg-[#1a1a2e] text-white">
      {/* Header */}
      <div className="flex items-center justify-between px-6 py-5 border-b border-white/10">
        <h1 className="text-xl font-bold tracking-widest">SIDEQUEST</h1>
        <button className="bg-white text-[#1a1a2e] text-sm font-semibold px-4 py-2 rounded-full">
          Sign up
        </button>
      </div>

      {/* Hero */}
      <div className="flex flex-col items-center text-center px-6 py-20">
        <div className="bg-white/10 text-sm px-4 py-1 rounded-full mb-6">
          Now available for friend groups
        </div>
        <h2 className="text-5xl font-bold mb-4 leading-tight">
          Challenges. Cash.<br />Bragging rights.
        </h2>
        <p className="text-white/60 text-lg max-w-md mb-10">
          Create a club, pool your money, and compete in daily random challenges. First to complete wins the pot.
        </p>
        <button className="bg-white text-[#1a1a2e] font-bold px-8 py-4 rounded-full text-lg">
          Create a club
        </button>
      </div>

      {/* Features */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 px-6 pb-20 max-w-4xl mx-auto">
        <div className="bg-white/5 rounded-2xl p-6 border border-white/10">
          <div className="text-3xl mb-3">💰</div>
          <h3 className="font-semibold text-lg mb-2">Prize pool</h3>
          <p className="text-white/50 text-sm">Everyone puts in money. Random challenges pay out slices throughout the club.</p>
        </div>
        <div className="bg-white/5 rounded-2xl p-6 border border-white/10">
          <div className="text-3xl mb-3">🎯</div>
          <h3 className="font-semibold text-lg mb-2">AI challenges</h3>
          <p className="text-white/50 text-sm">Challenges are generated by AI based on your club's vibe. Do a cartwheel. Convince a stranger to dance.</p>
        </div>
        <div className="bg-white/5 rounded-2xl p-6 border border-white/10">
          <div className="text-3xl mb-3">📸</div>
          <h3 className="font-semibold text-lg mb-2">Daily quest</h3>
          <p className="text-white/50 text-sm">Every day a group challenge drops. 2 minutes to capture it. Can't see others until you go.</p>
        </div>
      </div>
    </main>
  );
}